repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files: \.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: [--ignore-module, --fail-under=100, --whitelist-regex, "test_.*", tests]
  - repo: local
    hooks:
      - id: cogcheck
        name: cog --check
        additional_dependencies: [tox]
        entry: tox
        args: [run, -q, -e, cogcheck]
        language: python
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-toml
